### ISSUE TITLE
3ds max 2022 plugin? 

### ISSUE THREAD

**Issue by kiibu6000** [RemiArnaud/OpenCOLLADA#2]
Hello

Is there a 2022 plugin for 3ds max coming? 

Also how long is opencollada going to be used in the future? My environment uses opencollada 3d models. Since is seems that Kronos is no longer making new plugins, should i start to think about using glb/gltf instead?

**Comment by RemiArnaud** [comment]
Just think one step further. 

If Khronos is not maintaining COLLADA because they have moved to a new shiny ball, how long it will be till they decide gltf is not attractive anymore ans will go to the next shiny ball?

If you decide to switch format, you should consider this and use a format that looks like it is maintained by an organization that has incentive to maintain a format rather than incentive to create new formats.

**Comment by cyber-speed** [comment]
2022 support would come along great, do not give up on it, please keep up the great work.

Cheers.

**Comment by xtassin** [comment]
I second that. COLLADA is still part of my workflow and I would love to see a 2022 version of the plugin.

**Comment by RemiArnaud** [comment]
ok, please give this a try and let me know:
[Debug_Max2022.zip](https://github.com/RemiArnaud/OpenCOLLADA/files/7965529/Debug_Max2022.zip)
[Debug_Max2022_static.zip](https://github.com/RemiArnaud/OpenCOLLADA/files/7965531/Debug_Max2022_static.zip)
[Release_Max2022.zip](https://github.com/RemiArnaud/OpenCOLLADA/files/7965533/Release_Max2022.zip)
[Release_Max2022_static.zip](https://github.com/RemiArnaud/OpenCOLLADA/files/7965534/Release_Max2022_static.zip)

**Comment by xtassin** [comment]
Thank you Remi: this is working for me.

**Comment by cyber-speed** [comment]
It seems there's no chance to get it working for 3dsMax 2023, Autodesk always seems to break stuff, just for the fun of it.

Is there a chance we can get an update please?

No matter what i try 3dsMax's built in Autodesk Collada importer crashes on anything that is OpenCOLLADA assets.

**Comment by RemiArnaud** [comment]
https://github.com/RemiArnaud/OpenCOLLADA/releases/tag/v1.6.71-max
